source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Lightningkite/LKPodspec.git'
use_frameworks!
platform :ios, '9.0'

target 'LKAPI_Tests' do
  pod 'Alamofire', '~> 4.0'
  pod 'LKAPI', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
