source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Lightningkite/LKPodspec.git'
use_frameworks!
platform :ios, '9.0'

target 'LKAPI_Tests' do
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0-beta.2'  
  pod 'LKAPI', :path => '../'
end
